name: CommentClassifire

dependencies:
  - python=3.6.5
  - pip:
    - pandas==1.1.5
    - tqdm==4.62.3
    - matplotlib==3.3.4
    - numpy==1.19.5
    - requests==2.26.0
    - sentence-transformers==2.1.0
    - scikit-learn==0.24.2